[package]
name = "sagedoom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
const_format = "0.2.26"
crossterm = "0.24.0"
glium = "0.32.1"
itertools = "0.10.3"
winit = "0.27.1"
