#pragma once

#define DOOM_WIDTH 320ULL
#define DOOM_HEIGHT 200ULL

#define DOOM_RES_SCALE 4

#define DOOM_WINDOW_WIDTH (DOOM_WIDTH * DOOM_RES_SCALE)
#define DOOM_WINDOW_HEIGHT (DOOM_HEIGHT * DOOM_RES_SCALE)
